name = "Drakonix Tech Pack"
author = "Henry Post"
version = "0.0.4-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63d047ea695f5c411b3dfa239a0afbb96f43e487e3370209b03ea9d27a06e0c3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
