name = "Drakonix Tech Pack"
author = "Henry Post"
version = "0.0.29-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c774c6516d87d17c70b7619fe802c233a03720dc7ab3d6a1c6544fc70fa52a7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
