name = "Drakonix Tech Pack"
author = "Henry Post"
version = "0.0.21-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98512ef027d14e5815dfbcc54a77820807138a4b40cfab6e76aeb1f5041a2c58"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
